### ISSUE TITLE
NEED HELP! how to save a file in T-deck?

### ISSUE THREAD

**Issue by nullbeing** [shorepine/tulipcc#232]
I read the document says to save a fileineditor, press control+x
But there is no control key in the t-deck . So what can I do?

**Comment by bwhitman** [comment]
Check out the T-Deck page: https://github.com/bwhitman/tulipcc/blob/main/tulip/tdeck/README.md

It says 

>Control (for control-C, control-X (save in editor), etc) is set by pressing left-shift and the microphone/0 key at the same time. Release that combo and then hit the key you want. (like C, or X)

**Comment by bwhitman** [comment]
assuming this is resolved, thank you !
