### ISSUE TITLE
`waves.tar` is missing from Tulip World

### ISSUE THREAD

**Issue by infovore** [shorepine/tulipcc#291]
[Documentation](https://github.com/shorepine/tulipcc/blob/main/docs/music.md#outputting-cv-signals-to-modular-and-analog-synths) suggests you can `download('waves')` from Tulip World. However:

```
>>> world.download('waves')
Could not find waves.tar on Tulip World
```

Flagging this as an issue, rather than a discussion, simply because it's an action suggested in the documentation.

**Comment by infovore** [comment]
Update: `world.download('waves.py')` has the desired effect.

**Comment by bwhitman** [comment]
Oops! I'll fix the docs, thanks

**Comment by bwhitman** [comment]
thank you !
