### ISSUE TITLE
amy.stop() returns ImportError

### ISSUE THREAD

**Issue by jack2702** [shorepine/tulipcc#356]
Error retruned:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "amy.py", line 306, in stop
ImportError: no module named 'libamy'

**Comment by bwhitman** [comment]
Hi, can you give more information? What were you doing and what did you expect to happen? Have you installed the AMY python module first?

**Comment by bwhitman** [comment]
I just realized you've posted this in the Tulip issues list. Are you using a Tulip? If so, you don't need to ever call `amy.stop()`. It's always running on a Tulip. `amy.reset()` may be what you want.

**Comment by jack2702** [comment]
> I just realized you've posted this in the Tulip issues list. Are you using a Tulip? If so, you don't need to ever call `amy.stop()`. It's always running on a Tulip. `amy.reset()` may be what you want.
> 

Oh that makes sense. Thanks
